Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.default = {
    categories: [ {
        key: "all",
        cid: -1,
        label: "全部"
    }, {
        key: "tv",
        cid: 2,
        label: "电视剧"
    }, {
        key: "movie",
        cid: 1,
        label: "电影"
    }, {
        key: "zongyi",
        cid: 6,
        label: "综艺"
    }, {
        key: "dongman",
        cid: 4,
        label: "动漫"
    }, {
        key: "entertainment",
        cid: 7,
        label: "娱乐"
    }, {
        key: "fun",
        cid: 22,
        label: "搞笑"
    }, {
        key: "health",
        cid: 32,
        label: "健康"
    }, {
        key: "life",
        cid: 21,
        label: "生活"
    }, {
        key: "maternal",
        cid: 29,
        label: "母婴"
    }, {
        key: "talkShow",
        cid: 31,
        label: "脱口秀"
    }, {
        key: "military",
        cid: 28,
        label: "军事"
    }, {
        key: "trivia",
        cid: 10,
        label: "片花"
    }, {
        key: "travel",
        cid: 9,
        label: "旅游"
    }, {
        key: "fashion",
        cid: 13,
        label: "时尚"
    }, {
        key: "education",
        cid: 12,
        label: "教育"
    }, {
        key: "financial",
        cid: 24,
        label: "财经"
    }, {
        key: "music",
        cid: 5,
        label: "音乐"
    }, {
        key: "car",
        cid: 26,
        label: "汽车"
    }, {
        key: "record",
        cid: 3,
        label: "纪录片"
    }, {
        key: "sports",
        cid: 17,
        label: "体育"
    }, {
        key: "children",
        cid: 15,
        label: "儿童"
    }, {
        key: "game",
        cid: 8,
        label: "游戏"
    }, {
        key: "technology",
        cid: 30,
        label: "科技"
    } ],
    tabs: [ {
        index: 0,
        key: "realTime",
        label: "热度榜",
        isRealTime: !0
    }, {
        index: 1,
        key: "rise",
        label: "飙升榜",
        isRealTime: !0
    }, {
        index: 2,
        key: "playIndex",
        label: "播放指数榜",
        isRealTime: !1
    } ]
};